language: node_js

node_js:
  - "0.10"

install:
  - npm install spm@ninja coveralls mocha

before_script:
  - node_modules/spm/bin/spm-install
  - npm install

script:
  - node_modules/spm/bin/spm-test
  - node_modules/.bin/mocha -R spec tests/test.js

after_success:
  - node_modules/spm/bin/spm-test --coveralls | node_modules/.bin/coveralls
