os:
  - linux
  - osx
language: node_js

node_js:
  - "0.11.13"
  - "0.12"
  - "iojs-1"
  - "iojs-2"

install:
  - npm install spm coveralls mocha

before_script:
  - node_modules/spm/bin/spm-install
  - npm install

script:
  - make test

after_success:
  - cat coverage/lcov.info | node_modules/.bin/coveralls
